# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaskApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaskApp
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  pod 'Firebase/Auth'
  pod 'FirebaseUI'

  target 'TaskAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TaskAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
